---
Sigma: {'a', 'b', 'c'}
States:
  Q0:
    Transitions:
      q1: ['a']
      q2: ['c']
  Q1:
    Transitions:
      q2: ['b']
      q3: ['b']
  Q2:
    Final: True
  Q3:
    Transitions:
      q2: ['a']
